### ISSUE TITLE
Message Box in Description Screen

### ISSUE THREAD

**Issue by hbrooks7227** [bloghran618/SpotBird#21]
Add a message box or bold border around the "Description" input box. Spotbird green would look nice, (RGB Hex) is 63, BC,64).

**Comment by bloghran618** [comment]
This refers to SpotImageViewController().

I also think it might be nice to add a light gray boarder around the image

**Comment by bloghran618** [comment]
Both boarders should be light gray

**Comment by bloghran618** [comment]
Actually just do a boarder around the descriptino
