### ISSUE TITLE
Create an account (First name is not enough)

### ISSUE THREAD

**Issue by hbrooks7227** [bloghran618/SpotBird#25]
We need to have a more unique account name (there could be a ton of Henry's or Brian's that sign up) maybe we could add something interesting like ask them what their favorite bird is or something to create a unique ID.

**Comment by bloghran618** [comment]
This is something that Kevin is working on, I already notified him

**Comment by hbrooks7227** [comment]
Kevin Dave!!!

On Saturday, October 13, 2018, bloghran618 <notifications@github.com> wrote:
> Closed #25.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/xWaAK82ydeYFOw3DuYuDqn6kRBfZXBuv4OBEsrELikwE1ma89xI2xG3iVGFWBiyZPvjwUi_YP30g5z2yIH7wCHE5y8OJT2B6T70_cJG60e-F2lrnqxEguNz5b2WrInSjidxChiFkm0YwjQ1akuYKLAHHbxA5ew=s0-d-e1-ft#https://github.com/notifications/beacon/AmprUYkdeI4WE7RCRhg0bWW7U0kH8PnRks5uklXxgaJpZM4Xawpb.gif>
